<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Manufacturer\Models\Manufacturer;

class ManufacturerSeeder extends Seeder
{
    public function run(): void
    {
        // Source mapping data dari CPKO_RM_Manufacturers_with_Category.md
        // Format: 'Name' => ['category' => ..., 'material_type' => ...]
        $mappings = [
            'Adei Plantation & Industri, Duri' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Adhitya Serayakorita' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Aditya Agroindo' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Agro Bukit' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Agro Jaya Perdana' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Agro Sukses Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Alamraya Kencana Mas' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Aman Jaya Perdana' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Andes Agro Investama' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Asianagro Agung Jaya (PT. Aaj)' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Bangun Jaya Alam Permai' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Banyu Bening Utama' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Banyuasin Nusantara Sejahtera' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Batara Elok Semesta Terpadu' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Berdikari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Berkah Emas Sumber Terang' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Berkat Sawit Sejati' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Berlian Eka Sakti Tangguh (Best)' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Binapratama Sakatojaya Solok Selatan' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Bintang Era Sinar Tama (Best)' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Borneo Indah Marjaya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Buana Karya Bhakti' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Buana Tunas Sejahtera' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Buana Wira Lestarimas' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Budi Nabati Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Bukit Kapur Reksa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ceranti Subur' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Cipta Jaya Cemerlang' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Citra Agro Kencana' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Citra Borneo Utama' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Citrakoprasindo Tani' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Dharma Satya Nusantara Tbk' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Eka Dura Indonesia' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Energi Unggul Persada' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Era Karya Prima' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Gawi Makmur Kalimantan' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Global Interinti Industry' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Gunung Maras Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Gunung Mas Raya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Gunung Sejahtera Dua Indah' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Gunung Sejahtera Ibu Pertiwi' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Gunung Sejahtera Puti Pesona' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Harapan Sawit Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'IVomas Tunggal' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Indo Sepadan Jaya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Indonesia Plantation Synergy' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Intibenua Perkasatama, Riau' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Jalin Vaneo' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Just Oil' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'KCP PT. Betung' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'KCP PT. Sukses Karya Mandiri' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Karya Prajona Nelayan' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Karyanusa Ekadaya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kencana Agro Jaya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kencana Amal Tani' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ketapang Agro Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kimia Tirta Utama' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kodeco Agrojaya Mandiri' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kresna Duta Agroindo' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kurnia Tunggal Nugraha' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Kutai Refinery Nusantara' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Laguna Mandiri' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Letawa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'London Sumatera Indonesia' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Megah Hijau Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Mitra Aneka Rezeki' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Mitra Karya Usaha Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Multi Mas Nabati Asahan (K.Tanjung)' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Mutiara Bunda Jaya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Nubika Jaya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Awana Sawit Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Ayu Sawit Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Bukit Bintang Sawit' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Gawi Makmur Kalimantan' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Megah Hijau Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Mentari Sawit Makmur' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Pacrim Nusantara Lestari Foods' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Palma Mas Sejati' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Selatan Agro Makmur Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Sinar Tenggarong Inti Mulya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Teckno Dua Indonesia' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Paco Trading Co., Thailand' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Palm Trimitra Indotama' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Palma Bumi Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Pasangkayu' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Pelita Agung Agrindustri' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Peniti Sungai Purun' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Perkebunan Nusantara IV' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Permata Hijau Sawit' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Permata Subur Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ptpn III' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ptpn V' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ptpn VII' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Pulai Mill' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Putera Manunggal Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Putra Bangka Mandiri' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Rea Kaltim Plantations' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Rezeki Kencana' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sago Nauli' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Salim IVomas Pratama , Tbk' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sari Aditya Loka' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sari Dumai Sejati' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sari Lembah Subur' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Satya Kisma Usaha' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sawit Malinda' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sawit Sumbermas Sarana' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sawitra Oil Grains' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Alam Permai' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Bengkulu Inti Mulya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Jaya Inti Mulya (Kota Waringin)' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Jaya Inti Mulya (Lampung)' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Laut' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Sawit Sentosa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sinar Tayan Inti Mulya' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Smart Tbk' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Southern Palm Oil Industry, Thai' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Steelindo Wahana Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Sumber Indah Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Supra Matra Abadi' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Surya Mas Cipta Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Surya Raya Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Swadaya Mukti Prakarsa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Synergy Oil Nusantara' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Taluk Kuantan Perkasa' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Tayan Bukit Sawit' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Teguh Sempurna' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Th.Indo Plantations' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Tirta Madu Sawita' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Tropical Oil Product Pte., Ltd.' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Tunas Agro Subur Kencana' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Tunas Baru Lampung' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Usaha Inti Padang' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Victorindo Alam Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Wana Sawit Subur Lestari' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Waru Kaltim Plantation' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Wilmar Cahaya Indonesia Tbk, PT. - Pontianak' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Wira Inno Mas' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ceria Prima' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'PT. Hindoli' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Ramajaya Pramukti' => ['category' => 'RM', 'material_type' => 'CPKO'],
            'Mewah-Oils Sdn. Bhd.' => ['category' => 'RM', 'material_type' => 'CPKOlein (Crude Palm Kernel Olein)'],
            'PT. Synergy Oil Nusantara' => ['category' => 'RM', 'material_type' => 'CPKOlein (Crude Palm Kernel Olein)'],
        ];

        $manufacturers = [
            ['description' => '5-Continent Phosphorus Co., Ltd.'],
            ['description' => 'Adei Plantation & Industri, Duri'],
            ['description' => 'Adhitya Serayakorita'],
            ['description' => 'Aditya Agroindo'],
            ['description' => 'Aditya Birla Grasun Chem'],
            ['description' => 'Agro Bukit'],
            ['description' => 'Agro Jaya Perdana'],
            ['description' => 'Agro Sukses Lestari'],
            ['description' => 'Alamraya Kencana Mas'],
            ['description' => 'Ally Hydrogen Energy'],
            ['description' => 'Aman Jaya Perdana'],
            ['description' => 'American Natural Soda Ash Corporation'],
            ['description' => 'Andes Agro Investama'],
            ['description' => 'Aneka Gas'],
            ['description' => 'Anhui Herrman Imfex Co., Ltd.'],
            ['description' => 'Anhui Jinbang Medicine Chemical Co., Ltd.'],
            ['description' => 'Aochem International Limited'],
            ['description' => 'Apl Valueclay Pvt.Ltd.'],
            ['description' => 'Ar Razi (Saudi Methanol Company)'],
            ['description' => 'Asahimas Chemical'],
            ['description' => 'Ashland GmbH'],
            ['description' => 'Asianagro Agung Jaya (PT. Aaj)'],
            ['description' => 'Bangun Jaya Alam Permai'],
            ['description' => 'Banyu Bening Utama'],
            ['description' => 'Banyuasin Nusantara Sejahtera'],
            ['description' => 'Basf Aktiengesellschaft Inorganic Chemicals Europe'],
            ['description' => 'Basf Corporation'],
            ['description' => 'Basf Corporation / Basf Chemicals Company Ltd.'],
            ['description' => 'Basf Nederland B.V.'],
            ['description' => 'Basf Se, Inorganic Chemicals Europe'],
            ['description' => 'Basf Specialty Chemicals (Nanjing) Co., Ltd.'],
            ['description' => 'Batara Elok Semesta Terpadu'],
            ['description' => 'Berdikari'],
            ['description' => 'Berkah Emas Sumber Terang'],
            ['description' => 'Berkat Sawit Sejati'],
            ['description' => 'Berlian Eka Sakti Tangguh (Best)'],
            ['description' => 'Binapratama Sakatojaya Solok Selatan'],
            ['description' => 'Bintang Era Sinar Tama (Best)'],
            ['description' => 'Borneo Indah Marjaya'],
            ['description' => 'Brother Filtration Equipment Co., Ltd.'],
            ['description' => 'Brunei Methanol Co'],
            ['description' => 'BTSA Biotechnologias Aplicadas S. L.'],
            ['description' => 'Btsa, Biotecnologias Aplicadas, S.L.'],
            ['description' => 'Buana Karya Bhakti'],
            ['description' => 'Buana Tunas Sejahtera'],
            ['description' => 'Buana Wira Lestarimas'],
            ['description' => 'Buckman Asia Pacific Singapore'],
            ['description' => 'Budi Nabati Perkasa'],
            ['description' => 'Budi Starch & Sweetener Tbk'],
            ['description' => 'Bukit Kapur Reksa'],
            ['description' => 'Bulk Liquid Solution Pvt.Ltd.'],
            ['description' => 'Calgon Carbon'],
            ['description' => 'Calgon Carbon (Suzhou) Co., Ltd.'],
            ['description' => 'Calgon Carbon (Suzhou) Co., Ltd.; Suzhou Jiangsu'],
            ['description' => 'Calgon Carbon Corporation'],
            ['description' => 'Calgon Carbon Corporation, 3000 Gsk Drive , Moon Township, Pennsylvania 15108 USA'],
            ['description' => 'Calgon Carbon Corporation, Pittsburg, Pa USA'],
            ['description' => 'Calgon Carbon Corporation, Pittsburg, Pennsylvania USA'],
            ['description' => 'Calgon USA'],
            ['description' => 'Carbo Tech Ac GmbH'],
            ['description' => 'Carbotech Ac GmbH'],
            ['description' => 'Cargill Oil Mills Philippines, Inc'],
            ['description' => 'Ccm Chemicals'],
            ['description' => 'Ccm Chemicals Sdn Bhd'],
            ['description' => 'Ccm Chemicals Sdn, Bhd'],
            ['description' => 'Ceca Arkema Group'],
            ['description' => 'Century Chemical Sdn Bhd'],
            ['description' => 'Century Chemicals Workd Sdn Bhd'],
            ['description' => 'Ceranti Subur'],
            ['description' => 'Ceria Prima'],
            ['description' => 'Chemical Industries (Far East) Limited'],
            ['description' => 'China Chemical Industry'],
            ['description' => 'Chongqing Chuandong Chemical (Group) Co., Ltd.'],
            ['description' => 'Cipta Jaya Cemerlang'],
            ['description' => 'Citra Agro Kencana'],
            ['description' => 'Citra Borneo Utama'],
            ['description' => 'Citrakoprasindo Tani'],
            ['description' => 'Clariant Adsorbents Indonesia'],
            ['description' => 'Clariant Produkte (Deutschland) GmbH'],
            ['description' => 'Clariant Produkte GmbH'],
            ['description' => 'Clariants Adsorbents Indonesia'],
            ['description' => 'Cre Crem ( Qingdao) Limited'],
            ['description' => 'Cri Catalyst Leuna GmbH'],
            ['description' => 'Crytal Dignity (M) Sdn Bhd In Selangor'],
            ['description' => 'D&F Techniek'],
            ['description' => 'D&F Techniek B.V'],
            ['description' => 'Damai Uli Lestari'],
            ['description' => 'Davao Bay Coconut Oil Mills Inc.'],
            ['description' => 'Davy Process Technology Ltd.'],
            ['description' => 'Ddp Specialty Products Japan Kk (Dupont De Nemours,Inc) D/H Ddp Specialty Product Japan Kk (Dow Chemicals Japan Ltd.)'],
            ['description' => 'Degussa Ag / Evonik/Evonik Performance Materials GmbH'],
            ['description' => 'Deutsche Hydrierwerke GmbH'],
            ['description' => 'Dharma Satya Nusantara Tbk'],
            ['description' => 'Dhw'],
            ['description' => 'Donau Carbon GmbH &Co., Kg'],
            ['description' => 'Dongying Huatai Chemical Group Co., Ltd.'],
            ['description' => 'Dovechem Packaging Pte. Ltd.'],
            ['description' => 'Dovochem Packaging Pte., Ltd.'],
            ['description' => 'Dow Chemical Company USA'],
            ['description' => 'Dunia Kimia Jaya'],
            ['description' => 'Ecolab International Indonesia PT.'],
            ['description' => 'Edenor Oleochemicals (M) Sdn. Bhd'],
            ['description' => 'Eka Dura Indonesia'],
            ['description' => 'Emery'],
            ['description' => 'Energi Unggul Persada'],
            ['description' => 'Ep Mineral, Llc'],
            ['description' => 'Era Karya Prima'],
            ['description' => 'Evonik (SEA) Pte., Ltd.'],
            ['description' => 'Evyap Sabun Malaysia Sdn Bhd'],
            ['description' => 'Fahd Thanayyan Al Thanayyan&Partners , For Chemical Products Co., Ltd.'],
            ['description' => 'Filtrex Technology Pte. Ltd.'],
            ['description' => 'Fps Flexibles Vietnam Company Limited'],
            ['description' => 'Gawi Makmur Kalimantan'],
            ['description' => 'Genesis Alkali LLC. (American Natural Soda Ash Corporation)'],
            ['description' => 'German Saudi Industrial Company (Gesico)'],
            ['description' => 'Global Adsorbents Pvt Ltd.'],
            ['description' => 'Global Interinti Industry'],
            ['description' => 'Guangxi Chuan Jin Nuo Chemical Co., Ltd.'],
            ['description' => 'Guangxi Mingli Group'],
            ['description' => 'Guangxi Qinzhou Chengxing Chemical Technology Co., Ltd.'],
            ['description' => 'Guangzhou Huilong Filter Co., Ltd.'],
            ['description' => 'Guangzhou Sheng Wang Trading Co., Ltd.'],
            ['description' => 'Guizhou Sino-Phos Chemical Co., Ltd.'],
            ['description' => 'Gulf Petrochemical Industries Co., (Gpic)'],
            ['description' => 'Gunung Maras Lestari'],
            ['description' => 'Gunung Mas Raya'],
            ['description' => 'Gunung Sejahtera Dua Indah'],
            ['description' => 'Gunung Sejahtera Ibu Pertiwi'],
            ['description' => 'Gunung Sejahtera Puti Pesona'],
            ['description' => 'Haihang Industry Co., Ltd.'],
            ['description' => 'Haixing Eno Chemicals Co., Ltd.'],
            ['description' => 'Hanan Harvest Int'],
            ['description' => 'Hanwha Solutions Corporation'],
            ['description' => 'Harapan Sawit Lestari'],
            ['description' => 'Harriton Specialty Chemical Co., Ltd.'],
            ['description' => 'Haycarb Plc'],
            ['description' => 'Henan Sheng Hongfeng Chemical Co., Ltd.'],
            ['description' => 'Hinrich Industries Sdn., Bhd.'],
            ['description' => 'Honeywell Uop Nv Belgium'],
            ['description' => 'Hubei Xingfa Chemicals'],
            ['description' => 'Hubei Xingfa Chemicals Group Co., Ltd.'],
            ['description' => 'Huzhou Qiangda Molecular Sieve Technology Co., Ltd.'],
            ['description' => 'Iab Ionenaustauscher GmbH'],
            ['description' => 'Imerys Graphite And Carbon'],
            ['description' => 'Indo Sepadan Jaya'],
            ['description' => 'Indokarbon Primajaya (Inkaprimajaya, PT)'],
            ['description' => 'Indonesia Plantation Synergy'],
            ['description' => 'Indonesian Acid Industry'],
            ['description' => 'Induplex, Inc.'],
            ['description' => 'Industri Nabati Lestari'],
            ['description' => 'Insa-Alliance Sdn. Bhd.'],
            ['description' => 'International Methanol Comp'],
            ['description' => 'Intibenua Perkasatama, Riau'],
            ['description' => 'Ion Exchange (India) Limited'],
            ['description' => 'IVomas Tunggal'],
            ['description' => 'Jacobi Carbon Inc.'],
            ['description' => 'Jacobi Corbon Industry (Tianjin) Co., Ltd.'],
            ['description' => 'Jalin Vaneo'],
            ['description' => 'Java Taiko Mineralindo'],
            ['description' => 'Jaya Filter (M) Sdn., Bhd.'],
            ['description' => 'Jhonson Matthey Davy Technologies Limited'],
            ['description' => 'Jiangsu Chengxing Phosp Chemicals Co., Ltd.'],
            ['description' => 'Jiangxi Jinghao Salt Chemical Co., Ltd.'],
            ['description' => 'Jiangxi Xintao Technology Co., Ltd.'],
            ['description' => 'Jiaozuo Bisit Petrochem Co., Ltd.'],
            ['description' => 'Jinnan Forever Chemicals / Mercury Chemical Pte. Ltd.'],
            ['description' => 'Jnj Oleochemicals , Inc'],
            ['description' => 'Johnson Matthey Chemicals GmbH'],
            ['description' => 'Johnson Matthey Process Technologies'],
            ['description' => 'Johnson Mayyhey'],
            ['description' => 'JSC Europe Stabilizers, UAB'],
            ['description' => 'Just Oil'],
            ['description' => 'Kaltim Methanol Industri'],
            ['description' => 'Kapurindo Sentana Baja'],
            ['description' => 'Karbon Prima Sentosa Abadi'],
            ['description' => 'Karya Indah Alam Sehajtera'],
            ['description' => 'Karya Prajona Nelayan'],
            ['description' => 'Karyanusa Ekadaya'],
            ['description' => 'Katalis Sinergi Indonesia'],
            ['description' => 'Kawaguchi Chemical Industry'],
            ['description' => 'KCP PT. Betung'],
            ['description' => 'KCP PT. Sukses Karya Mandiri'],
            ['description' => 'Kekwa Indah Sdn Bhd'],
            ['description' => 'Kencana Agro Jaya'],
            ['description' => 'Kencana Amal Tani'],
            ['description' => 'Ketapang Agro Lestari'],
            ['description' => 'Kimia Tirta Utama'],
            ['description' => 'King Lee Technologies Inc'],
            ['description' => 'Kirin Separation DBA Clear Edge Filtration Malaysia Sdn., Bhd.'],
            ['description' => 'KL Kepongg Oleomas Sdn Bhd'],
            ['description' => 'Kodeco Agrojaya Mandiri'],
            ['description' => 'Kresna Duta Agroindo'],
            ['description' => 'Kujang Sud Chemie Catalyst PT. (PT. Clariant Kujang Catalysts)'],
            ['description' => 'Kurnia Tunggal Nugraha'],
            ['description' => 'Kutai Refinery Nusantara'],
            ['description' => 'Laguna Mandiri'],
            ['description' => 'Lanxess Bmbh'],
            ['description' => 'Lanxess Deutchland GmbH'],
            ['description' => 'Lanxess Deutschland GmbH'],
            ['description' => 'Lanxess GmbH'],
            ['description' => 'Lautan Luas Singapore Pte., Ltd.'],
            ['description' => 'Letawa'],
            ['description' => 'Lg Chem. Ltd.'],
            ['description' => 'Lhoist Spn Sdn. Bhd'],
            ['description' => 'London Sumatera Indonesia'],
            ['description' => 'Mahkota Indonesia'],
            ['description' => 'Mahkota Jaya Raya'],
            ['description' => 'Malay Sino Chemical Iindustries Sdn, Bhd'],
            ['description' => 'Malay Sino Chemical Industries Sdn, Bhd'],
            ['description' => 'Malaysino Chemical Industries Sdn, Bhd'],
            ['description' => 'Mauser Singapore Pte. Ltd.'],
            ['description' => 'Megah Hijau Lestari'],
            ['description' => 'Megah Puti Raya Soda Sumatera'],
            ['description' => 'Merck Kgaa'],
            ['description' => 'Mercury Chemical Pte. Ltd.'],
            ['description' => 'Mercury Pte., Ltd.'],
            ['description' => 'Methanex Chile SpA'],
            ['description' => 'Mewah-Oils Sdn. Bhd.'],
            ['description' => 'Mitra Aneka Rezeki'],
            ['description' => 'Mitra Karya Usaha Perkasa'],
            ['description' => 'Multi Mas Nabati Asahan (K.Tanjung)'],
            ['description' => 'Multi Nabati Sulawesi'],
            ['description' => 'Musim Mas'],
            ['description' => 'Mutiara Bunda Jaya'],
            ['description' => 'My Flexitank Industries Sdn., Bhd.'],
            ['description' => 'Nagamas Palmoil Lestari'],
            ['description' => 'Nanning Chemical Group'],
            ['description' => 'National Methanol Company'],
            ['description' => 'Nissan Girdler'],
            ['description' => 'Norit Netherland B.V.'],
            ['description' => 'Nsl Chemicals Ltd.'],
            ['description' => 'Nubika Jaya'],
            ['description' => 'Oman Methanol Company Llc'],
            ['description' => 'One Flexitank Industries Sdn Bhd'],
            ['description' => 'Optimus Flexitank Solutions Sdn., Bhd'],
            ['description' => 'Oq Methanol Company'],
            ['description' => 'P&G'],
            ['description' => 'Pabrik Kertas Tjiwi Kimia , Tbk'],
            ['description' => 'Pacinesia Chemical Industry'],
            ['description' => 'Pacinesia Chemical Industry (Berubah Ke PT. Lautan Air Indonesia)'],
            ['description' => 'Paco Trading Co., Thailand'],
            ['description' => 'Palm Oleo Sdn., Bhd'],
            ['description' => 'Palm Trimitra Indotama'],
            ['description' => 'Palma Bumi Lestari'],
            ['description' => 'Pasangkayu'],
            ['description' => 'Pelita Agung Agrindustri'],
            ['description' => 'Peltech Filtration Sdn., Bhd.'],
            ['description' => 'Peniti Sungai Purun'],
            ['description' => 'Perkebunan Nusantara IV'],
            ['description' => 'Perkin Hannifin Corp'],
            ['description' => 'Perlite Indonesia Abadi Pt'],
            ['description' => 'Permata Hijau Palm Oleo'],
            ['description' => 'Permata Hijau Palm Oleo Unit Kim-2'],
            ['description' => 'Permata Hijau Sawit'],
            ['description' => 'Permata Subur Lestari'],
            ['description' => 'Perstorp'],
            ['description' => 'Petronas Chemicals Derivatives Sdn Bhd'],
            ['description' => 'Petronas Chemicals Methanol Sdn Bhd'],
            ['description' => 'Petronas Chemicals Methanol Sdn., Bhd.'],
            ['description' => 'Pgeo Edible Oils Sdn Bhd'],
            ['description' => 'Pindo Deli Pulp And Paper Mills'],
            ['description' => 'Pingxiang Hongshun Environmental Protection Technology Co., Ltd.'],
            ['description' => 'Pingxiang Zhongxing Packing Co., Ltd.'],
            ['description' => 'PKS Aek Raso'],
            ['description' => 'PKS Betung'],
            ['description' => 'PKS Lubuk Dalam'],
            ['description' => 'PKS Sei Baruhur'],
            ['description' => 'PKS Sei Daun'],
            ['description' => 'PKS Sei Garo'],
            ['description' => 'PKS Sei Intan'],
            ['description' => 'PKS Sei Meranti'],
            ['description' => 'PKS Sei Rokan'],
            ['description' => 'PKS Sei Tapung'],
            ['description' => 'PKS Sei Torgamba'],
            ['description' => 'PKS Sungai Lengi'],
            ['description' => 'PKS Talang Sawit'],
            ['description' => 'PKS Tandun'],
            ['description' => 'PKS Terantam'],
            ['description' => 'Polygel Industries Pvt Ltd.'],
            ['description' => 'Polygel Organometallic (Brunai) Sdn. Bhd'],
            ['description' => 'Poms Ventures, Filipina'],
            ['description' => 'Pro-Flex Packaging Zhongshan Limited'],
            ['description' => 'PT Dwi Karya Bentonit Indonesia'],
            ['description' => 'PT. Andes Agro Investama (PT. Maya Agro Investama)'],
            ['description' => 'PT. Andes Agro Investama (PT. Poliplant Sejahtera)'],
            ['description' => 'PT. Asahimas Chemical'],
            ['description' => 'PT. Awana Sawit Lestari'],
            ['description' => 'PT. Ayu Sawit Lestari'],
            ['description' => 'PT. Bukit Bintang Sawit'],
            ['description' => 'PT. Bumi Karyatama Raharja'],
            ['description' => 'PT. Castrol Indonesia'],
            ['description' => 'PT. Cipta Lestari Sawit'],
            ['description' => 'PT. Clariant Adsorbents Indonesia'],
            ['description' => 'PT. Clariant Kujang Catalysts'],
            ['description' => 'PT. Dunia Kimai Jaya'],
            ['description' => 'PT. Energi Sejahtera Mas'],
            ['description' => 'PT. Evonik Indonesia'],
            ['description' => 'PT. First Lamandau Timber International'],
            ['description' => 'PT. Gawi Makmur Kalimantan'],
            ['description' => 'PT. Gawi Makmur Kalimantan - Satui'],
            ['description' => 'PT. Gunung Tua Abadi'],
            ['description' => 'PT. Hindoli'],
            ['description' => 'PT. Ikaindo Ndustri Karbonik Indonesia'],
            ['description' => 'PT. Karya Indah Alam Sejahrera'],
            ['description' => 'PT. Karyaindah Alam Sejahtera'],
            ['description' => 'PT. Katalis Sinergi Indonesia'],
            ['description' => 'PT. Kurita Indonesia'],
            ['description' => 'PT. Lanang Agro Bersatu'],
            ['description' => 'PT. Lautan Air Indonesia'],
            ['description' => 'PT. Mahkota Jaya Raya'],
            ['description' => 'PT. Megah Hijau Lestari'],
            ['description' => 'PT. Mentari Sawit Makmur'],
            ['description' => 'PT. Mitra Mendawai Sejati'],
            ['description' => 'PT. Musim Mas'],
            ['description' => 'PT. Mutiara Bunda Jaya'],
            ['description' => 'PT. Nusaraya Permai'],
            ['description' => 'PT. Pabrik Kertas Tjiwi Kimia , Tbk'],
            ['description' => 'PT. Pacrim Nusantara Lestari Foods'],
            ['description' => 'PT. Palma Mas Sejati'],
            ['description' => 'PT. Pam Palm Oil Mill'],
            ['description' => 'PT. Parna Agromas'],
            ['description' => 'PT. Permata Hijau Palm Oleo'],
            ['description' => 'PT. Petrocentral'],
            ['description' => 'PT. Pgeo Edible Oils Sdn., Bhd.'],
            ['description' => 'PT. Pindo Deli Pulp  & Paper'],
            ['description' => 'PT. Pindodeli Pulp And Paper Mills'],
            ['description' => 'PT. Polytech Indo Hausen'],
            ['description' => 'PT. Pupuk Kujang'],
            ['description' => 'PT. Pupuk Sriwijaya Palembang'],
            ['description' => 'PT. Sampoerna Agro Tbk.'],
            ['description' => 'PT. Sari Dumai Oleo'],
            ['description' => 'PT. Sawit Sumbermas Sarana'],
            ['description' => 'PT. Schutz Container Systems Indonesia'],
            ['description' => 'PT. Selatan Agro Makmur Lestari'],
            ['description' => 'PT. Sinar Tenggarong Inti Mulya'],
            ['description' => 'PT. Socimas'],
            ['description' => 'PT. Synergy Oil Nusantara'],
            ['description' => 'PT. Teckno Dua Indonesia'],
            ['description' => 'PT. Telaga Hikmah'],
            ['description' => 'PT. Wilmar Nabati Indonrsia'],
            ['description' => 'Ptpn III'],
            ['description' => 'Ptpn V'],
            ['description' => 'Ptpn VII'],
            ['description' => 'Pulai Mill'],
            ['description' => 'Pulau Sambu, Kuala Enok'],
            ['description' => 'Pupuk Kaltim'],
            ['description' => 'Pupuk Kujang'],
            ['description' => 'Purolite'],
            ['description' => 'Purolite (China) Co., Ltd.'],
            ['description' => 'Purolite Company'],
            ['description' => 'Putera Manunggal Perkasa'],
            ['description' => 'Putra Bangka Mandiri'],
            ['description' => 'Qatar Fuel Additives Co., Ltd.'],
            ['description' => 'Qatar Fuel Additives Co., Ltd. (Qafac)'],
            ['description' => 'Qatar Vinyl Company Ltd. , Distributed By Qatar Chemical And Petrochemical Marketing And Distribution Company (Muntajat)'],
            ['description' => 'Qingdao Blt Packing Industrial Co., Ltd.'],
            ['description' => 'Qingdao Blt Solution Flexitank Co., Ltd.'],
            ['description' => 'Qingdao Global Flexitank Logistic Co., Ltd.'],
            ['description' => 'Qingdao Laf Technology Co., Ltd.'],
            ['description' => 'Qingdao Let Flexitank Co., Ltd.'],
            ['description' => 'Qingdao Redbutterfly Precision Materials Co., Ltd.'],
            ['description' => 'Qingdao Tongseng Packing Co., Ltd.'],
            ['description' => 'Qizhong Chemical Industry (Zhengzhou) Co., Ltd.'],
            ['description' => 'Qpack Industries Sdn,Bhd.'],
            ['description' => 'Ramajaya Pramukti'],
            ['description' => 'Rci (Lime) Sdn Bhd'],
            ['description' => 'Rea Kaltim Plantations'],
            ['description' => 'Rezeki Kencana'],
            ['description' => 'Rohm & Haas Chemicals Llc Japan'],
            ['description' => 'RZBC (Juxian) Co., Ltd. Exported By RZBC Imp And Exp.Co., Ltd.'],
            ['description' => 'Sago Nauli'],
            ['description' => 'Salim IVomas Pratama , Tbk'],
            ['description' => 'Samator Intiperoksida'],
            ['description' => 'Samsung Fine Chemicals Co., Ltd.'],
            ['description' => 'Sari Aditya Loka'],
            ['description' => 'Sari Dumai Sejati'],
            ['description' => 'Sari Lembah Subur'],
            ['description' => 'Sari Mas Permai'],
            ['description' => 'Sasol Chemicals (USA) Llc'],
            ['description' => 'Sasol Place'],
            ['description' => 'Satya Kisma Usaha'],
            ['description' => 'Saudi Basic Industries Corporation (Sabic)'],
            ['description' => 'Sawit Malinda'],
            ['description' => 'Sawit Sumbermas Sarana'],
            ['description' => 'Sawitra Oil Grains'],
            ['description' => 'Schutz Malaysia Sdn., Bhd.'],
            ['description' => 'See Sen Chemical Sdn Bhd/ Ccm Sdn Bhd'],
            ['description' => 'See Sen Chemicals Sdn Bhd/ Ccm Sdn Bhd'],
            ['description' => 'Shandong Ensign Industry'],
            ['description' => 'Shandong Ensign Industry Co., Ltd.'],
            ['description' => 'Shandong Hairong Chemical Technology Co., Ltd.'],
            ['description' => 'Shandong Hairong Chemical Technology Co., Ltd., Supplied By Qingdao Julihecheng Industry &Trade Co., Ltd.'],
            ['description' => 'Shandong Haoyu Industrial Technology Co., Ltd'],
            ['description' => 'Shandong Jiahua Water Treatment Technology Co., Ltd.'],
            ['description' => 'Shandong New Source Chemical Co., Ltd.'],
            ['description' => 'Shandong Perstorp Chemical Co., Ltd.'],
            ['description' => 'Shenzhen Yihaodi Import And Export Co., Ltd.'],
            ['description' => 'Shifang Changfeng Chemical Co., Ltd.'],
            ['description' => 'Shifang Zhixin Chemical Co., Ltd.'],
            ['description' => 'Shijiazhuang Jackchem Co., Ltd.'],
            ['description' => 'Shiram Alkali &Chemicals (Dcm Shriam Ltd.)'],
            ['description' => 'Shuzou Rovathin'],
            ['description' => 'Sichuan Chuansin Chemical'],
            ['description' => 'Sichuan Ronghong Technology Development Co., Ltd.'],
            ['description' => 'Sinar Alam Permai'],
            ['description' => 'Sinar Bengkulu Inti Mulya'],
            ['description' => 'Sinar Jaya Inti Mulya (Kota Waringin)'],
            ['description' => 'Sinar Jaya Inti Mulya (Lampung)'],
            ['description' => 'Sinar Laut'],
            ['description' => 'Sinar Sawit Sentosa'],
            ['description' => 'Sinar Tayan Inti Mulya'],
            ['description' => 'Sinergi Sinar Sejahtera'],
            ['description' => 'Sino-Linchem Co., Ltd.'],
            ['description' => 'Smart Tbk'],
            ['description' => 'Socimas'],
            ['description' => 'Solutia Inc'],
            ['description' => 'Solvay Peroxythai Limited'],
            ['description' => 'Southern Palm Oil Industry, Thai'],
            ['description' => 'Steelindo Wahana Perkasa'],
            ['description' => 'Sterlitamak Petrochemical Plant , Ojsc'],
            ['description' => 'Sud Chemia India (P) Ltd.'],
            ['description' => 'Sud Chemie Ag'],
            ['description' => 'Sud Chemie Ag / Clariant Produkte(Deutschland)GmbH'],
            ['description' => 'Sud Chemie India Pvt Ltd.'],
            ['description' => 'Sud Chemie India Pvt Ltd. Exported By Clariant Produkte (Deutschland) GmbH'],
            ['description' => 'Sudchemie Indonesia, PT. / PT. Clariant Adsorbents Indonesia'],
            ['description' => 'Sulfindo Adiusaha'],
            ['description' => 'Sumatraco Langgeng Makmur'],
            ['description' => 'Sumber Indah Perkasa'],
            ['description' => 'Sun Plan Development'],
            ['description' => 'Sunresin New Materials Co., Ltd.'],
            ['description' => "Sunresin New Materials Co., Ltd. Xi' An"],
            ['description' => 'Supra Matra Abadi'],
            ['description' => 'Surya Mas Cipta Perkasa'],
            ['description' => 'Surya Raya Lestari'],
            ['description' => 'Swadaya Mukti Prakarsa'],
            ['description' => 'Synergy Oil Nusantara'],
            ['description' => 'Taekwang Industrial Co., Ltd. .Petrochemical 2Nd Plant'],
            ['description' => 'Taiko Drum Industries Sdn. Bhd.'],
            ['description' => 'Taluk Kuantan Perkasa'],
            ['description' => 'Tayan Bukit Sawit'],
            ['description' => 'Teguh Sempurna'],
            ['description' => 'Th.Indo Plantations'],
            ['description' => 'Thai Peroxide Co., Ltd.'],
            ['description' => 'Tianjin Xincheng Salt Factory'],
            ['description' => 'TIB Chemicals'],
            ['description' => 'Tib Chemicals S.A. De C.V.'],
            ['description' => 'Timuraya Tunggal'],
            ['description' => 'Tirta Madu Sawita'],
            ['description' => 'Tjiwi Kimia Tbk'],
            ['description' => 'Toba Pulp Lestari,Pt'],
            ['description' => 'Toray Bluestar Membrane Co., Ltd.'],
            ['description' => 'Tropical Oil Product Pte., Ltd.'],
            ['description' => 'Ttca Co., Ltd.'],
            ['description' => 'Tunas Agro Subur Kencana'],
            ['description' => 'Tunas Baru Lampung'],
            ['description' => 'Uci Utama'],
            ['description' => 'Unid Co., Ltd.'],
            ['description' => 'Usaha Inti Padang'],
            ['description' => 'Utama Inti Hasil Kimia Industri'],
            ['description' => 'Vdh Chem Tech Pvt .Ltd.'],
            ['description' => 'Victorindo Alam Lestari'],
            ['description' => 'Wana Sawit Subur Lestari'],
            ['description' => 'Waru Kaltim Plantation'],
            ['description' => 'Weifang Ensign Industry Co., Ltd.'],
            ['description' => 'Weifang Toption Chemical Industry Co.,Ltd.'],
            ['description' => 'Wengfu Group Co., Ltd.'],
            ['description' => 'Wilmar Cahaya Indonesia Tbk, PT. - Pontianak'],
            ['description' => 'Wilmar Nabati Indonesia'],
            ['description' => 'Wira Inno Mas'],
            ['description' => 'Wuhan Hengyetong Gas Equipment Co., Ltd.'],
            ['description' => 'Wuhan Ycd International Co., Ltd. / Hunan Yunfeng Technology Co., Ltd.'],
            ['description' => 'Xinyang Wanda New Material Co., Ltd.'],
            ['description' => 'Yangzhou Chemical Co., Ltd.'],
            ['description' => 'Yantai Hui Heng Packaging Co., Ltd.'],
            ['description' => 'Yatai Chemicals Corp'],
            ['description' => 'Yong Lin Industrial Co., Ltd.'],
            ['description' => 'YSHC Co., Ltd.'],
            ['description' => 'Yunnan Chengilang Dean Phosporus'],
            ['description' => 'Yunnan Tin Chemical Co., Ltd.'],
            ['description' => 'Yunnan Xiangfeng Chemical Fertilizer Co., Ltd.'],
            ['description' => 'Yunphos International Trading'],
            ['description' => 'Zehua Chemtec International Ltd.'],
            ['description' => 'Zenith Chemicals Corporation'],
            ['description' => 'Zhengzhou Mahaco Industrial Co., Ltd.'],
            ['description' => 'Zhengzhou Saihang Chemcal Technology Co., Ltd.'],
            ['description' => 'Zhuhai Senbo Cryogenic Energy Equipment Co., Ltd.'],
            ['description' => 'Zibo Beige Industry and Crade Co., Ltd.'],
            ['description' => 'Zibo Taida Chemical Co., Ltd.'],
            ['description' => 'Zibo Win-Ceramic Material Co., Ltd.'],
            ['description' => 'Zico Jingchuan Environmental Protection Material Co., Ltd.'],
        ];

        foreach ($manufacturers as $data) {
            $desc = $data['description'];
            $cat = null;
            $matType = null;
            if (isset($mappings[$desc])) {
                $cat = $mappings[$desc]['category'];
                $matType = $mappings[$desc]['material_type'];
            }

            Manufacturer::firstOrCreate(
                ['description' => $desc],
                [
                    'category' => $cat,
                    'material_type' => $matType,
                    'status' => 1,
                    'created_by' => 'Michael Sutanto',
                    'updated_by' => 'Michael Sutanto',
                ]
            );
        }
    }
}
